### ISSUE TITLE
Error when opening file created using the test page

### ISSUE THREAD

**Issue by a-h** [evidenceprime/html-docx-js#1]
Failed to open up a file created using the test tool at http://evidenceprime.github.io/html-docx-js/test/sample.html

![openfailure](https://cloud.githubusercontent.com/assets/1029947/5854035/651f5e96-a221-11e4-96bf-9947198fb96d.png)

**Comment by a-h** [comment]
Test document at https://drive.google.com/file/d/0By6nm3ACZguvM2FPekZsVjlfamM/view?usp=sharing

**Comment by jtowers** [comment]
Per the docs:
> "IMPORTANT: please pass a complete, valid HTML (including DOCTYPE, html and body tags). This may be less convenient, but gives you possibility of including CSS rules in style tags."

When I include all of that in the demo, it generates a file that works fine for me.

**Comment by anowak** [comment]
Yes, that is right. This is slightly embarrassing that the demo doesn't reflect what was written in the documentation, I will fix this soon.

**Comment by a-h** [comment]
I just typed some text in the HTML textbox on the screen as a test, to decide whether to proceed with testing the code further.

Taking a look again I didn't think it's clear that to get the demo to work, one needs to edit the HTML to add a doctype, html and body tags.

**Comment by a-h** [comment]
Nice, thanks!

**Comment by aymanar** [comment]
This is still causing problems. 
Can you give us an example of a valid HTML to test on?

**Comment by anowak** [comment]
@aymanar The current demo adds HTML tags automatically (this is the fix I've deployed), so it is no longer necessary to add them yourself. Please remember that it only works when opened in MS Word though.

**Comment by CoDEmanX** [comment]
I just created some content on the demo page, downloaded the docx but Word (Office 2013) only gives me an error. Am I overlooking something obvious?
