### ISSUE TITLE
SaveAs error while converting html to docx

### ISSUE THREAD

**Issue by nanthak** [evidenceprime/html-docx-js#10]
I have used the following code to generate docx file.
               var htmlDocx = require('html-docx-js');
               var content = 'businesscard.html';    
               var converted = htmlDocx.asBlob();
               saveAs(converted, 'test.docx');

But i got an error that says, saveAs is not defined. I don't know what todo now?
need some help. 
Thanks in advance.

**Comment by anowak** [comment]
Please include https://github.com/eligrey/FileSaver.js/ to use `saveAs` in the way described in README.md.

Also please note that the `content` should be a full HTML document and that you would need to pass it as an argument to `asBlob` method.

**Comment by nanthak** [comment]
Hi anowak,

I need soulution for the same in node.js. If it is front end, then i will do it. More over i have used the same in angular.js . But my need is to  use this in my node.js app, means i want to use it in node's html-docx-js module. Hope you understand. If you know anything regarding this pls comment here.

Thanks.

**Comment by anowak** [comment]
In node.js, you receive a `Buffer` that you can then save to a file in the following way:

```
var docx = HtmlDocx.asBlob(html);
fs.writeFile(outputFile, docx, function(
  if (err) throw err;
});
```

In this repository you can find a complete sample for node.js usage: https://github.com/evidenceprime/html-docx-js-node-sample

**Comment by nanthak** [comment]
Thanks. But no data has displayed in the generated or converted docx file. My simple code is ,

     var htmlDocx = require('html-docx-js');
     var content = ''pages/dummy.html',
     console.log(content);
     var out =  'Docx/out1.docx';
     console.log(out);
     fs.readFile(content, 'utf-8', function(err, html) {
        if (err) throw err;

        var docx = htmlDocx.asBlob(html);
        fs.writeFile(out, docx, function(err) {
            if (err) throw err;
            else{
                console.log("Docx has been created");
            }
        });
      });

**Comment by anowak** [comment]
As I already indicated in my first comment, you need to pass a **full HTML document** to `asBlob` method. Your file (`pages/dummy.html`) does not contain `<html>` tag (for instance)

**Comment by nanthak** [comment]
Sorry, i forget to add the entire html.  Here is my full html source. Though i pass full html my response is empty.

    <!DOCTYPE html>
    <html>
    <head lang="en">
    <meta charset="UTF-8">
    <title></title>
   </head>
    <body>
   <table border="" style="width: 100%;" cellspacing="0" cellpadding="6">
    <tr style="background-color: #b3b3b3;">
        <th align="left"><b>S.No</b></th>
        <th align="left"><b>Verification</b></th>
        <th align="left"><b>Details</b></th>
        <th align="left"><b>Status</b></th>
    </tr>

    <tr>
        <td><b>1</b></td>
        <td><b>Present Address</b></td>
        <td><b>Tuticorin</b></td>
        <td style="color: orange">Unable to verify</td>
    </tr>
    </table>
    </body>
    </html>

**Comment by anowak** [comment]
What application do you use to open the resulting file? Please be advised that only relatively recent versions of Microsoft Word are supported (see `README.md` for the details).

**Comment by sivagurun55** [comment]
Hi anowak,

       var content='dummy.html';
      var converted = htmlDocx.asBlob(content);
      saveAs(converted, 'test.docx');


dummy.html
<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>

</body>
</html>


Downloaded file was empty. As i followed everything as readme file

**Comment by dinesh-rawat-dev** [comment]
This issue shouldn't be closed, as the issue is still present

**Comment by anowak** [comment]
What application do you use to open the resulting file? See `README.md` for supported editors.

**Comment by paulhands** [comment]
Unless I'm missing something the README does not explain you also need to install FileSaver.js
