### ISSUE TITLE
Converting AltChunk to "Standard" Docx

### ISSUE THREAD

**Issue by aviv-or** [evidenceprime/html-docx-js#114]
First, Thanks for working on this library, it has helped me a lot with my project.

My apologies if I'm using the wrong terms. I understand that this library generates an HTML version of a docx document, and that its currently not supported by Google Docs, Open office, Word for Mobile and many other readers that don't support AltChunk.

Do you know a way to convert the file so it can be supported by these readers? I'm open to any solution in any programming language. I've tried looking for something, but couldn't find anything.

Thanks in advance :)

**Comment by brockfanning** [comment]
I believe this is also what #74 was about. I don't have a solution, though I understand that manually editing and saving the file in Microsoft Word (specifically) does the trick.

For another related discussion in a separate project, see https://github.com/mwilliamson/mammoth.js/issues/71

**Comment by anowak** [comment]
Unfortunately, the solution provided by @brockfanning is the only that comes to my mind. This possibly could be automated in .NET, but deploying MS Word on a server is [quite problematic](https://support.microsoft.com/en-us/help/257757/considerations-for-server-side-automation-of-office).

**Comment by aviv-or** [comment]
My application also generates PDF, the DOCX file is just a bonus. 
I've ended up hiding the DOCX conversion button on mobile and non-windows OS which seems the most logical solution to this problem from a user-experience perspective.

But I still appreciate your help on this

**Comment by anowak** [comment]
No problem, I'm closing this issue. Please reopen if you find it necessary.

**Comment by Mena489** [comment]
Please is there any solution to this?
