### ISSUE TITLE
Does not work in readers other than ms word

### ISSUE THREAD

**Issue by dev7abhi** [evidenceprime/html-docx-js#12]
I need to convert docx for a whole different reason. I want html page in my java application to be converted to docx file and your script can do this but the issue is I cannot open it within the application which is the important part of the process. I want a docx file created which can be read using docx4j library i.e. a general docx. Please tell me if that's possible and how?

**Comment by anowak** [comment]
It all depends on whether altchunks are supported by the library of your choice. [This SO answer](http://stackoverflow.com/a/22907714/706171) seems to suggest that docx4j supports XHTML altchunks. Maybe the doctype is an issue here? Certainly something out of the scope of this library, though.
