### ISSUE TITLE
A4 page

### ISSUE THREAD

**Issue by martinlazarov** [evidenceprime/html-docx-js#18]
Hello everyone!
First I want to thank you for the great lib you have created! Awesome! :)))

I have an issue when I try to add content with minimum height of one A4 page (29.7 cm). What I need in my DOCX is to have couple of blocks of texts, every of each to be on separate page. Example: Chapter I will be on the first page, Chapter II no the 2nd, Chapter III - 3rd and etc... I wrapped the block with height of 29.7 cm (style="height: 29.7cm") but it didn't work. The block's height is as much as its content - not 29.7 cm.
How can accomplish this or is there another way to do it?
Thank you!

**Comment by N1kto** [comment]
From your request it is not very clear what you want to achieve: a) have each chapter start from a new page or b) have Word respect your `height` directives.

If you are about the first case, then all you need is to use `page-break-*` CSS directive. For example, your chapter title is a simple `<p class="chapter-title>Awesome chapter...</p>`. Add the following CSS rule inside `<style>` tags of your document:
`page-break-before: always !important;`

This will make all your chapters start from a new page.
Regarding the second problem - I doubt that approach you are using has any sense as `cm` is not a real/physical `1 cm` on paper, it depends on `dpi` setting of printer or screen resolution.

Hope that clarifies.
