### ISSUE TITLE
Using html-docx-js with electron

### ISSUE THREAD

**Issue by aessig** [evidenceprime/html-docx-js#21]
Hi, 
I'm using electron 0.34.2, and when I try to export a docx file, it seams to work but the docx file only contain the following: 
`[object Blob]`
Here is my code: 

```
var converted = HtmlDocx.asBlob(html_document, {orientation: 'portrait'});

fs.writeFile(path, converted, function(err) {
 if (err) throw err;
});
```

When I run the same code only using nodejs it work correctly.
Cheers

**Comment by spyshow** [comment]
did you find a solution for  this ??

**Comment by N1kto** [comment]
@spyshow  did you look into  #25?

**Comment by spyshow** [comment]
thank you .... i didn't notice it.

**Comment by anowak** [comment]
Duplicate of #25
