### ISSUE TITLE
Save the output blob to a file 

### ISSUE THREAD

**Issue by azain** [evidenceprime/html-docx-js#25]
Thanks for this awesome package, it will solve me a lot of problems :)

Now, I am using it in NodeJs, and all is file, the problem is that I don't know how to save the return of .asBlob to a file, it comes out something like [blob object] ! Here is my code

```
                // Renders the HTML template
                var html = this.render(template, values);

                // Convert the html to open xml format
                var output = html2docx.asBlob(html, {
                    'margins': {'top': 200}
                });

                console.log(output);

                // Save the output
                fileSystem.writeFileSync(outputFile, output);
```

Here is the output object contents
![capture](https://cloud.githubusercontent.com/assets/13228056/13202237/f9fd0836-d89b-11e5-9d46-fb9382cad07c.PNG)

What should i change to get it to save this "blob" to a file ? 
Thanks

**Comment by anowak** [comment]
In node.js environment, there is no such thing as `Blob` (there is `Buffer` instead), so your output seems to suggest that you execute the code in a browser.

Please refer to https://github.com/evidenceprime/html-docx-js-node-sample for an example how to use the library on the server.

**Comment by azain** [comment]
Oh, I forgot to tell you that I am using Electron. I will have a second look and get back to you, thanks :)

**Comment by N1kto** [comment]
@azain has never come back Assume the problem was resolved.

**Comment by tamkeen-tms** [comment]
Yes actually. Instead of requiring the library through Node.js I called it in the HTML file the App will be showing, as a javascript asset. And it's working just fine.

**Comment by MuhammedAlkhudiry** [comment]
> 
> 
> Yes actually. Instead of requiring the library through Node.js I called it in the HTML file the App will be showing, as a javascript asset. And it's working just fine.

"I called it" you called what exactly?

**Comment by tamkeen-tms** [comment]
> > Yes actually. Instead of requiring the library through Node.js I called it in the HTML file the App will be showing, as a javascript asset. And it's working just fine.
> 
> "I called it" you called what exactly?

The library, what else could it be?!
