### ISSUE TITLE
Output file blank in Pages (Mac) and Google Documents

### ISSUE THREAD

**Issue by lamuertepeluda** [evidenceprime/html-docx-js#26]
Wonderful library. I don't know if this is really an issue of html-docx-js, but I've tried both online demo and node.js version. Works fine with [Word Online](https://office.live.com/start/Word.aspx) and MS Word for Windows but I get a blank sheet when opening the generated file with Pages or Google Documents.

Is this perhaps using a different format than the standard one?

**Comment by anowak** [comment]
Unfortunately, the mechanism that we use is only supported by Microsoft Word at the moment. It is written in README.md, although we will make it more prominent and also mention incompatibility with Pages.
