### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by thowar2** [evidenceprime/html-docx-js#27]
This seems to be no longer working. The demo generates an empty .docx file, and trying to use it locally does the same.

Anyone still have it working?

**Comment by iansoper** [comment]
+1 I'm having the same problem

**Comment by anowak** [comment]
What word processor do you use to open the .docx file? Please note that only MS Word is supported.

**Comment by thowar2** [comment]
I opened it with Apple Pages and Google Docs. Both will normally open other .docx files, are the ones generated by this different?

**Comment by anowak** [comment]
Unfortunately, yes. From the README.md:

> Altchunks were not supported by Microsoft Word for Mac 2008 and are not supported by LibreOffice and Google Docs.

I will make this sentence more prominent and add information about Pages.
