### ISSUE TITLE
"Document is damaged" on Word App

### ISSUE THREAD

**Issue by LoicMahieu** [evidenceprime/html-docx-js#31]
Thanks for this great library. We use it in a one of our project and it works great appart for one thing.

When we generate the docx from an iPad (with Safari on the latest version of iOS), we get a blank page returned. If we open this in the Word App (published by Microsoft), we get a « Document is damaged » warning.
We’ve try with the online demo  http://evidenceprime.github.io/html-docx-js/test/sample.html as well, but it does seems that this issue appear here too.

Do you have any work around to have Word document that could work on iOS ?

![img_0001 2](https://cloud.githubusercontent.com/assets/900947/15572797/29621c46-2343-11e6-8080-3b4c8e3756e5.PNG)

**Comment by anowak** [comment]
We haven't tested if Word for iOS supports altchunks feature that is crucial for our solution to work. I will do some research and get back to you.

Thank you for bringing this to my attention!

**Comment by anowak** [comment]
Our investigation shows that the iOS app is really a wrapper around Word Online, so it has the same problems in handling altchunks. The bottom line is that unfortunately it won't work until Microsoft adds this feature to Word Online.
