### ISSUE TITLE
CSS3 Flexbox not working ?

### ISSUE THREAD

**Issue by AlexGiroud** [evidenceprime/html-docx-js#33]
![issuegithub](https://cloud.githubusercontent.com/assets/8853344/16375606/817ffaf6-3c5c-11e6-9640-31a59c5f40b5.PNG)

Your lib is great, but i've tried to render a doc styled with flexbox and the layout didn't responded like i expected. Is it already a known issue or is it just me doing things wrong ?
All the styling is in the HTML and not in <style> tags.
Left side is the render in html, right in docx with the lib.

**Comment by N1kto** [comment]
@AlexGiroud unfortunately not all CSS properties are supported by MS Word.
Even `CSS 2.1` is not supported in full. Same is fair for `flex-` properties.

When writing styles, you can refer to [this](https://msdn.microsoft.com/en-us/library/aa338201%28office.12%29.aspx#Word2007MailHTMLandCSS_Full) document to double check if some particular CSS property is supported.
