### ISSUE TITLE
cyrillic text

### ISSUE THREAD

**Issue by IgorFilippov3** [evidenceprime/html-docx-js#34]
Hello, unfortunately, if i will type cyrillic letters it will give back something like this ""Р°РІС‹Р°РІС‹Р"

**Comment by N1kto** [comment]
Checked on [our test page.](http://evidenceprime.github.io/html-docx-js/test/sample.html) 
Generated file is here: [test.docx](https://github.com/evidenceprime/html-docx-js/files/357308/test.docx).

All is fine. Please share more details.

**Comment by IgorFilippov3** [comment]
Your example really works fine, but I against of usin poor tinyMCE I am using angular-ui-tinyMCE. I suppose that the main problem is here. Mb, if text to convert reciev from the angular ng-model don't converted as a text reciev from html? Or it is madness?

**Comment by N1kto** [comment]
html-docx-js works with plain HTML as an input. The lib charset is UTF-8, so it works fine with Cyrillic (as you saw in provided file).

Did you check how the HTML you send to html-docx-js looks like, does it look OK or does it already contain ""Р°РІС‹Р°РІС‹Р"?

I will close the issue for now as I don't recognize this to be a problem of the html-docx-js. We can continue the discussion though.
