### ISSUE TITLE
Live demo downloads blank document

### ISSUE THREAD

**Issue by austince** [evidenceprime/html-docx-js#35]
The downloaded files are all blank. Not sure if this is a me problem. Using Chrome v54.0.2816.0 dev (64-bit) on Ubuntu 14.04
Also running into problems using the node package with v6.2.1 
Using v0.3.1 and v0.2.2 of html-docx-js.

This seems to be a problem with LibreOffice. Do you support/will you support LibreOffice in the future?

**Comment by anowak** [comment]
We don't support LibreOffice at the moment and unfortunately the ball is in their court. We use some specific feature of WordprocessingML (the markup language of DOCX files) that is not handled by LibreOffice while opening DOCX files.

**Comment by austince** [comment]
Ah, alright. Thanks for the feedback!
