### ISSUE TITLE
Accent characters are not rendering correctly in Word 2007

### ISSUE THREAD

**Issue by ferrx** [evidenceprime/html-docx-js#36]
Hi,

I am trying to export some HTML (using IE11) and currently testing with Word 2007. I am seeing accent characters like  "é" displaying as "Ã©" in the exported document. If I copy/paste the exact text on my HTML page into the same document, it renders fine.

Any help would be appreciated.

Thanks,
Steven

**Comment by N1kto** [comment]
@ferrx this can be a problem with encoding set in consumer (i.e. Word 2007 your try to open file in).
Can you attached a file with described issue?

The generated document content is encoded in utf8, so should generally work. 

I tried putting mentioned letter ("é") on our [demo](http://evidenceprime.github.io/html-docx-js/test/sample.html) page. Generated file has **proper** character (checked on Word 2010 though).

**Comment by ferrx** [comment]
Thanks- I assumed it may be an issue with Word 2007. I will test it in another version (though my users currently require 2007 support). I am wondering if there is some setting that I could flip in Word 2007 to have this import correctly.. that could be a fix that I can offer my users temporarily.

**Comment by N1kto** [comment]
You can check out [this](https://support.office.com/en-us/article/Choose-text-encoding-when-you-open-and-save-files-00c46cde-83a4-437d-be83-aca280ff9174) article.

**Comment by masterpoi** [comment]
I had the same thing with Word 2016. Turns out you need `<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>` in your html.

**Comment by ferrx** [comment]
@masterpoi Thank you!! This fixed it for me.

**Comment by MCTaylor17** [comment]
I had this problem too.  Adding the meta tag suggested by @masterpoi worked correctly.

If this isn't an option for whatever reason, you can also replace the offending characters with html entities which seem to work "out-of-the-box".
