### ISSUE TITLE
Sample Not working in Chrome

### ISSUE THREAD

**Issue by harshalcse** [evidenceprime/html-docx-js#39]

**Comment by N1kto** [comment]
Works on my machine. What platform, Chrome version are you using?

**Comment by sferoze** [comment]
@N1kto yah I used the demo at this link: http://evidenceprime.github.io/html-docx-js/test/sample.html

The downloaded work down opens in Google Docs as blank file. Also opens as blank in Apple Pages. 

The library isnt working for me either in chrome.

**Comment by fyodorio** [comment]
Doesn't work for me too (blank file). MacOS Sierra, Chrome 58.0.3029.110 (64-bit).

**Comment by N1kto** [comment]
Sorry guys, but the generated file is compatible only with MS WORD* word processor. It will not work (will be blank) if opened in LibreOffice, Google Docs, etc since there is no `altChunks` support in those applications.

-* from README:
> Altchunks were not supported by Microsoft Word for Mac 2008 and are not supported by LibreOffice and Google Docs.

**Comment by edencorbin** [comment]
Im seeing this too, works in word, but not in libre office, is there no plan for libre office support?

**Comment by anowak** [comment]
@edencorbin Unfortunately, this is something they would need to add on their side.
