### ISSUE TITLE
The sample doesn't work

### ISSUE THREAD

**Issue by Dracks** [evidenceprime/html-docx-js#49]
Hello, 

I test, and the sample it's showing nothing in libreoffice, It seems to work with word, but should be good to can open it with libreoffice (or openoffice)

**Comment by anowak** [comment]
Unfortunately, the mechanism we use is not supported by LibreOffice. See README:

> Altchunks were not supported by Microsoft Word for Mac 2008 and are not supported by LibreOffice and Google Docs
