### ISSUE TITLE
Table in exported word document is not formatted

### ISSUE THREAD

**Issue by PrathyushaNarayanan** [evidenceprime/html-docx-js#52]
I'm using html-docx-js to convert a document from html to a word document. The issues seen in the resultant document are as listed below:

1. The exported file has the content of the html file. However, the content within tables does not retain it's formatting(The content displayed isn't in sync with the column titles). 

2. The string 'Column Settings' is prepended to each column title.

3. The title of the 1st column is prepended to the title of every subsequent column of the table.

The js code used is:
------
var contentDocument = document.getElementById(ids[i]);
                var content = '<!DOCTYPE html>' + contentDocument.outerHTML;
                var converted = htmlDocx.asBlob(content, {orientation: 'landscape', margins: {top: 720}});

                saveAs(converted, ids[i]+'.docx');

                var link = document.createElement('a');
                link.href = URL.createObjectURL(converted);
                link.download = ids[i];
                link.appendChild(
                    document.createTextNode('Click here if your download has not started automatically'));
                var downloadArea = document.getElementById('download-area');
                downloadArea.innerHTML = '';
                downloadArea.appendChild(link);
------

Can anyone help with any pointers towards resolving this issue?

**Comment by anowak** [comment]
Exporting tables _generally_ works, because we export mostly tables in our software ourselves. The problem is that MS Word is not as good at rendering complex tables as a browser.

Could you try exporting a very simple, unstyled table first and then gradually adding styling? It is a little bit of hit or miss, but there is no other way.

**Comment by anowak** [comment]
Closing as we haven't heard back and there is nothing we can do to help. I will add an example with a styled table tough.
