### ISSUE TITLE
ENOENT: no such file or directory, open //assets/content_types.xml

### ISSUE THREAD

**Issue by po5i** [evidenceprime/html-docx-js#59]
Fresh install with yarn and get the following error when executing asBlob method:

`Uncaught Error: ENOENT: no such file or directory, open '//assets/content_types.xml'    at Object.fs.openSync (fs.js:558:18)`

Using
Electron: 1.6.7
React: 15.5.4
Webpack: 2.4

**Comment by jfaquinojr** [comment]
As a workraound, I copied the contents of /node_modules/html-docx-js/src/assets to my own /src/assets and it worked.

**Comment by ghost** [comment]
You are importing the wrong module. The module you are importing is for use with node.

If you use `import htmlDocx from "html-docx-js/dist/html-docx";` instead, it should import the correct version (assuming youre going to use this in the render process of your application.)
