### ISSUE TITLE
Incorrect package.json "main" option?

### ISSUE THREAD

**Issue by vilic** [evidenceprime/html-docx-js#6]
It's now "src/index.coffee", and it's not working for me. Shouldn't we change that into "dist/html-docx.js"?

**Comment by anowak** [comment]
How do you use the package? This entry is intended for use either with node.js or Browserify. The problem with using `dist/html-docx.js` is that it contains browser-specific code.

**Comment by vilic** [comment]
I'm testing it on node. https://docs.npmjs.com/files/package.json#devdependencies

I see, so I should use the file compiled from index.coffee for node usage?

**Comment by anowak** [comment]
Yes, you are right, I totally overlooked this. The new version is published correctly. You can also refer to https://github.com/evidenceprime/html-docx-js-node-sample for a minimal example of how to use it.

**Comment by vilic** [comment]
Great to know, thanks! :smile:
