### ISSUE TITLE
table row height

### ISSUE THREAD

**Issue by Avijobo** [evidenceprime/html-docx-js#62]
I am not able to reduce the table row height... default there is too much margin/padding space, however I am not able to reduce that, setting CSS margin/padding does not seem to have any effect on table row height... also tried text-height, however that only chops off the font. Any suggestions?

**Comment by shiloma** [comment]
Got the same Problem, still no solution?

Edit: got the solution, just put a p-element around the text with style="display:inline; margin:0px;"

**Comment by Avijobo** [comment]
Never found a solution... thanks for sharing!
