### ISSUE TITLE
Error msg : html_docx_1.default is undefined

### ISSUE THREAD

**Issue by Linpter** [evidenceprime/html-docx-js#72]
Hi,

I'd like to have some enlightenment on the error i have encountered.

I just try for the first time html-docx-js in my app in Angular 5. I'm retrieving a enriched text from [QuillJS](https://quilljs.com/) with a HTML format, and then trying to transform this data with html-docx-js. The purpose is to register it in my db and then retrieve it whenever i want to make a file .docx with it.

Issue : When i'm trying to transform my text (with html format from QuillJS), using html-docx, i'm facing this error : **html_docx_1.default is undefined**
But i don't understand to what html_docx_1 it is refering. Is it the text i'm giving to him ? Can someone help me to understand ?

Here is my code : 
.typescript
```
onClickSaveText() {
    let html = this.quill.container.firstChild.innerHTML;
    let finalHtml = '<html><head><meta charset="UTF-8"></head><body>';
    finalHtml += html;
    finalHtml += '</body></html>';
    let converted = htmlDocx.asBlob(finalHtml);
// service posting the converted text
    this.textSvc.postText(converted, this.passDataSvc.getCrId())
       .subscribe(answer => console.log('From save button', answer));
}
```

Of course i've added this to my html : 
<script src="htmldocx/html-docx.js"></script>
<script src="htmldocx/Blob.js"></script>

Thank you

**Comment by anowak** [comment]
It seems to me that you don't have a TypeScript declaration file for our library. We don't provide it ourselves. If you could contribute one, it would be superb!

**Comment by Linpter** [comment]
You mean an import ? Yeah i forgot to put it there but i'm importing it with :

import htmlDocx from 'html-docx-js/dist/html-docx';

**Comment by Linpter** [comment]
Oh wait, i think i misread your answer. You meant that there is no currently typescript declaration file four your lib and i should create it. Oh ok ! I can try. But i'm still a dev student but i can definitely try to contribute.

**Comment by N1kto** [comment]
@PaulMalifarge did you try a "named" import like this: 
`import { asBlob } from 'html-docx-js';`

And then in your handler:  `asBlob(finalHtml);`

The lib was written as CommonJS module (not ES6 module), so it doesn't have `.default` export.

**Comment by anowak** [comment]
@PaulMalifarge please ignore my comment, I was led astray by the TypeScript thing and I thought that this cryptic error comes from it. Please see @N1kto comment above.

**Comment by Linpter** [comment]
@N1kto I'm not sure to understand what you mean about the handler, because i have already this `asBlob(finalHtml);` in.

So currently i'm trying with named imports as below:
```
import { htmlDocx } from 'html-docx-js/dist/html-docx';
import { asBlob } from 'html-docx-js'; 
```

But i've still got the same error. I just realized that my IDE (webstorm) is telling me that it cannot find the asBlob declaration. Ok so i guess that's my issue. 

By the way, thank you guys for your wonderful reactivity. It is very appreciated.

**Comment by salceson** [comment]
```
import { asBlob } from 'html-docx-js/dist/html-docx';
```
Try only this import, it should work.

**Comment by PaulMalifarge** [comment]
Hi @salceson 
I think i still need the htmldocx import, otherwise i get an error that 

> htmlDocx is not defined

Using those two : 
```
import { htmlDocx } from 'html-docx-js/dist/html-docx';
import { asBlob } from 'html-docx-js/dist/html-docx';
```
Is not working also. I'm facing a slightly different error : 
> html_docx_1.htmlDocx is undefined

instead of 
> html_docx_1.default is undefined

But it seems like the import is still not working

**Comment by PaulMalifarge** [comment]
asBlob when used alone is recognized by the import. ex : `let converted = asBlob(finalHtml);` does not generate error. Am i missing something ?

**Comment by Linpter** [comment]
Ok i just understood ! Pardon my noobness...i did not understand the syntax until now. Thank everyone !  AsBlob is working fine alone with just his import.

**Comment by anowak** [comment]
Great to hear this!
