### ISSUE TITLE
Generating blank documents

### ISSUE THREAD

**Issue by ajouve** [evidenceprime/html-docx-js#74]
I am trying to use this module on node.js

```js
const htmlDocx = require('html-docx-js');
const fs = require('fs');

const converted = htmlDocx.asBlob('<h1>hi</h1><p>abcd</p>');

fs.writeFileSync('test.docx', converted);
```

The `test.docx` is generated but blank, the `converted` is not an empty buffer

**Comment by somename85** [comment]
same

**Comment by somename85** [comment]
It blank at ubuntu 16.04, node 8.11, 8.7.4, but work good at macOS with node 8.11.
upd. It blank in [onlyoffice](https://www.onlyoffice.com/) and google docs, in ms office it looks good.

**Comment by anowak** [comment]
I suppose you are using LibreOffice to open the result on Ubuntu. Documents generated using this library can only be opened using Microsoft Word.

See README.md

> Altchunks were not supported by Microsoft Word for Mac 2008 and are not supported by LibreOffice and Google Docs.

**Comment by yasaricli** [comment]
hello @ajouve ;

I had a problem like this, but I solved it by converting it on the server side.

You can use it: https://github.com/yasaricli/html-docx
