### ISSUE TITLE
Running client side

### ISSUE THREAD

**Issue by DirkSimons** [evidenceprime/html-docx-js#78]
Is there any way to run this client side?   I keep hitting the `fs.readFileSync is not a function` error when only doing the conversion. (`var converted = htmlDocx.asBlob(content)`) 
Anyone have an idea how to resolve this.

**Comment by anowak** [comment]
Duplicate of #51 

In short: you either need to polyfill the `fs` module (using Browserify or something else) or use our bundle with batteries included: `html-docx-js/dist/html-docx`.
