### ISSUE TITLE
How to pass cookies with html?

### ISSUE THREAD

**Issue by MrManojSingh** [evidenceprime/html-docx-js#84]
I have some image url in html with require cookie value to display. So i can achieve this case?

**Comment by anowak** [comment]
Cookies are realized using HTTP headers. You cannot set them in HTML. Word won't have access to the cookies that were sent to the browser.

The only solution is to download the image while still in the browser, serialize it to a data URI and include in the HTML (see `convertImagesToBase64` in the demo to see how to do this).
