### ISSUE TITLE
Font is ignored in tables

### ISSUE THREAD

**Issue by anne7** [evidenceprime/html-docx-js#9]
Is there a way to have tables respect fonts?  I have tried putting the style in the TABLE tag,  the TH and TD  tags, and in a SPAN around the content itself.  It works on my mac, but on windows the content inside the table is showing up with the default Word font (Calibri).

**Comment by anowak** [comment]
What `font-family` are you trying to use? Maybe Word has some problem mapping it to the system font? I created an example file with the following content and everything worked fine with Word 2003 for Windows. In our [application](gdt.guidelinedevelopment.org), we also generate tables with `<span>` styled with a our custom symbol font and it works without problems.

```
<!DOCTYPE html>
<html>
<head></head>
<body>
<table style="height: 73px;" width="235">
<tbody>
<tr>
<td style="text-align: center; font-family: Arial;">ABCDEF</td>
</tr>
</tbody>
</table>
</body>
</html>
```

**Comment by anne7** [comment]
Your example works for me too.  It also worked when I changed Arial to "Times," which is what we are using.  Maybe something else in our stylesheet is causing it to not work, so I will investigate further.  Thank you for looking in to it!

**Comment by anowak** [comment]
Great to hear this!
