### ISSUE TITLE
Empty file on https

### ISSUE THREAD

**Issue by myuce** [evidenceprime/html-docx-js#94]
So we've just switched to https on our servers and now whenever I download a file, Word doesn't show anything, not even a blank page. Has anyone ever had this issue before? You can see how it works on the page below.

https://qb.canakkaleakd.com/ws/suhBrG263bo/?print=true

**Comment by myuce** [comment]
The issue seems to have fixed itself and I have no idea how it worked. I'll update the issue should it happen again.

**Comment by anowak** [comment]
OK, please reopen if necessary.
