### ISSUE TITLE
some styling issues

### ISSUE THREAD

**Issue by thiagorova** [evidenceprime/html-docx-js#98]
Hi, and first of all thanks a lot for this awesome package.
One small question... Identation changes are not being applied to the docx, are they? I just tested here locally and on the online test system you guys have, but it just didn't work.
Any ideas on this?

**Comment by thiagorova** [comment]
ok, I discovered a work around this problem. If you use `indent_use_margin: true` option, things work perfectly. It seems that word just doesn't understand the concept of padding, which is pretty ok.

I'm gonna close this, as there is a pretty viable solution. Feel free to contact me if you want to know something else.
Thanks again!

**Comment by thethirddan** [comment]
@thiagorova I'm having a problem with tables in word. It's adding a default spacing : after of 8pt. How can I set that to 0pt with HTML or CSS? I've tried a bunch of things...

**Comment by thiagorova** [comment]
Hi! I'm sorry, but I'm not 100% sure what you mean. Do you mean you're having a space after your <td> content? could you show me an html example?

I just tested copying a table into the [test page](http://evidenceprime.github.io/html-docx-js/test/sample.html) and generating a docx. I wasn't able to notice anything particularly odd. My suggestion is to remove all your CSS files from the styling and see if the problem remains. If not, try adding them one by one back in. Perhaps this error is being caused by some other styling of yours (which may be why your other tests failed)

hope this helps

**Comment by thangkieu** [comment]
Hi @thiagorova! I checked on MS Word for Mac, it looks fine. but when I tried to open by MS Word 2017 on Windows, there is spacing after 8pt, it makes the table cell doesn't middle align.
![image](https://user-images.githubusercontent.com/4321996/82167622-fb102880-98ee-11ea-8b11-079c7a9c172c.png)
![image](https://user-images.githubusercontent.com/4321996/82167641-095e4480-98ef-11ea-91f6-d8ea14cc3159.png)
I exported the files from [http://evidenceprime.github.io/html-docx-js/test/sample.html](http://evidenceprime.github.io/html-docx-js/test/sample.html)
